/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: d6525cb5fa74c504e57134fec09e159b)
interface __BaseEnv_Env {
	MEDIA_BUCKET: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
